export const GAME_ROUNDS = [
  {
    id: "sg-orchard-road",
    name: "Orchard Road",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Easy",
    clueTypes: ["retail corridor", "English signage", "dense city"],
    reveal: "Orchard Road is Singapore's best-known shopping belt, so polished malls, wide sidewalks, and English-heavy signs are strong clues.",
    fact: "The Orchard district began as an area of nutmeg, pepper, and fruit orchards before becoming a retail spine.",
    lat: 1.303989,
    lng: 103.83345,
    imageUrl: "./assets/rounds/sg-orchard-road.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Orchard_Road,_Singapore_(June_26,_2023)_pedestrians.jpg",
    attribution: "Sharon Hahn Darlin, CC BY 2.0"
  },
  {
    id: "th-bangkok-khao-san-road",
    name: "Khao San Road",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["Thai script", "backpacker street", "street market"],
    reveal: "Thai script, dense shopfronts, and backpacker-market energy point toward Bangkok's Khao San Road.",
    fact: "Khao San Road became internationally famous as a backpacker hub near Bangkok's old city.",
    lat: 13.759738,
    lng: 100.495676,
    imageUrl: "./assets/rounds/th-bangkok-khao-san-road.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Khao_San_Road,_Bangkok,_Tailandia_(37594114336).jpg",
    attribution: "Edgardo W. Olivera, CC BY 2.0"
  },
  {
    id: "th-phuket-bangla-road",
    name: "Bangla Road",
    city: "Phuket",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["Thai script", "nightlife", "tourist strip"],
    reveal: "Bangla Road's nightlife signage and Patong resort feel separate it from Bangkok's older street markets.",
    fact: "Bangla Road sits in Patong, one of Phuket's busiest nightlife and beach districts.",
    lat: 7.893422,
    lng: 98.297367,
    imageUrl: "./assets/rounds/th-phuket-bangla-road.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bangla_Road_Patong_Thajsko_2018_4.jpg",
    attribution: "Karelj, Public domain"
  },
  {
    id: "my-kuala-lumpur-jalan-alor",
    name: "Jalan Alor",
    city: "Kuala Lumpur",
    country: "Malaysia",
    difficulty: "Easy",
    clueTypes: ["food stalls", "Chinese signage", "Malaysia flag"],
    reveal: "Jalan Alor is a food street in Bukit Bintang; mixed Chinese/English signage and Malaysian flags are useful tells.",
    fact: "Jalan Alor is one of Kuala Lumpur's best-known open-air dining streets.",
    lat: 3.145644,
    lng: 101.708619,
    imageUrl: "./assets/rounds/my-kuala-lumpur-jalan-alor.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jalan_Alor_Kuala_Lumpur.jpg",
    attribution: "Alexander Synaptic, CC BY-SA 4.0"
  },
  {
    id: "vn-hcmc-bui-vien",
    name: "Bui Vien Street",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    difficulty: "Medium",
    clueTypes: ["Vietnamese signage", "night street", "dense shopfronts"],
    reveal: "Vietnamese diacritics on signs and the narrow nightlife street scene point toward Bui Vien in Ho Chi Minh City.",
    fact: "Bui Vien is often called Ho Chi Minh City's backpacker street.",
    lat: 10.766556,
    lng: 106.692111,
    imageUrl: "./assets/rounds/vn-hcmc-bui-vien.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bui_Vien_Street,_Ho_Chi_Minh_City,_at_night,_2023_(07).jpg",
    attribution: "Bahnfrend, CC BY-SA 4.0"
  },
  {
    id: "kh-siem-reap-pub-street",
    name: "Pub Street",
    city: "Siem Reap",
    country: "Cambodia",
    difficulty: "Medium",
    clueTypes: ["tourist street", "English signage", "low-rise shophouses"],
    reveal: "Pub Street's tourist-facing English signs and Siem Reap shophouse look distinguish it from bigger capitals.",
    fact: "Pub Street is a nightlife and restaurant area near the Angkor temple tourism circuit.",
    lat: 13.360173,
    lng: 103.856122,
    imageUrl: "./assets/rounds/kh-siem-reap-pub-street.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pub_Street,_Siem_Reap.jpg",
    attribution: "Radoslaw Botev, CC BY 3.0 PL"
  },
  {
    id: "vn-hanoi-ta-hien",
    name: "Ta Hien Street",
    city: "Hanoi",
    country: "Vietnam",
    difficulty: "Hard",
    clueTypes: ["Old Quarter", "Vietnamese signage", "narrow street"],
    reveal: "Narrow lanes, older facades, and Vietnamese signage are a strong Hanoi Old Quarter pattern.",
    fact: "Ta Hien is one of Hanoi Old Quarter's best-known social streets.",
    lat: 21.034711,
    lng: 105.852142,
    imageUrl: "./assets/rounds/vn-hanoi-ta-hien.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:T%E1%BA%A1_Hi%E1%BB%87n_Street,_Hanoi,_Vietnam_13.jpg",
    attribution: "Ltn12345, CC BY-SA 4.0"
  },
  {
    id: "my-malacca-jonker-walk",
    name: "Jonker Walk",
    city: "Malacca",
    country: "Malaysia",
    difficulty: "Medium",
    clueTypes: ["heritage street", "Chinese signage", "colonial shophouses"],
    reveal: "The heritage arch, shophouses, and mixed Chinese/Malaysian visual language point to Jonker Walk.",
    fact: "Jonker Walk runs through Malacca's UNESCO-listed historic core.",
    lat: 2.198153,
    lng: 102.244692,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Malacca_Malaysia_Jonker-Walk-Arch-and-Tamil-Methodist-Church-01.jpg/1920px-Malacca_Malaysia_Jonker-Walk-Arch-and-Tamil-Methodist-Church-01.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Malacca_Malaysia_Jonker-Walk-Arch-and-Tamil-Methodist-Church-01.jpg",
    attribution: "CEphoto, Uwe Aranas, CC BY-SA 3.0"
  },
  {
    id: "ph-makati-avenue",
    name: "Makati Avenue",
    city: "Metro Manila",
    country: "Philippines",
    difficulty: "Hard",
    clueTypes: ["English signage", "CBD skyline", "wide avenue"],
    reveal: "English-heavy urban signage and the dense Makati business district feel point toward Metro Manila.",
    fact: "Makati is one of the Philippines' major financial and commercial centers.",
    lat: 14.552662,
    lng: 121.023137,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Makati_Avenue%2C_Feb_2025.jpg/1920px-Makati_Avenue%2C_Feb_2025.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Makati_Avenue,_Feb_2025.jpg",
    attribution: "Ralff Nestor Nacor, CC BY-SA 4.0"
  },
  {
    id: "id-jakarta-sudirman",
    name: "Jalan Sudirman",
    city: "Jakarta",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["business district", "Indonesian road name", "high-rise corridor"],
    reveal: "The wide CBD corridor and Indonesian 'Jalan' road naming are strong Jakarta clues.",
    fact: "Jalan Sudirman is part of Jakarta's central business spine.",
    lat: -6.210986,
    lng: 106.819795,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Jalan_Sudirman%2C_Jakarta_-_panoramio.jpg/1920px-Jalan_Sudirman%2C_Jakarta_-_panoramio.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jalan_Sudirman,_Jakarta_-_panoramio.jpg",
    attribution: "Mozhar, CC BY-SA 3.0"
  },
  {
    id: "id-yogyakarta-malioboro",
    name: "Malioboro Street",
    city: "Yogyakarta",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["Indonesian signage", "arcades", "heritage shopping street"],
    reveal: "Malioboro's covered walkways and Indonesian street-market feel mark it as Yogyakarta.",
    fact: "Malioboro is one of Yogyakarta's most famous shopping and cultural streets.",
    lat: -7.7926,
    lng: 110.3658,
    imageUrl: "./assets/rounds/id-yogyakarta-malioboro.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Malioboro_Street,_Yogyakarta.JPG",
    attribution: "Gunawan Kartapranata, CC BY-SA 3.0"
  },
  {
    id: "sg-ion-orchard",
    name: "ION Orchard",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Easy",
    clueTypes: ["luxury mall", "English signage", "clean streetscape"],
    reveal: "ION Orchard's distinctive mall frontage and English-heavy shopping corridor are very Singapore.",
    fact: "ION Orchard is one of the landmark malls along Orchard Road.",
    lat: 1.304342,
    lng: 103.831772,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/ION_Orchard_and_Orchard_Road%2C_Singapore_%2842345667100%29.jpg/1920px-ION_Orchard_and_Orchard_Road%2C_Singapore_%2842345667100%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ION_Orchard_and_Orchard_Road,_Singapore_(42345667100).jpg",
    attribution: "Fabio Achilli, CC BY 2.0"
  },
  {
    id: "th-bangkok-khao-san-market",
    name: "Khao San Road Market",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["Thai script", "souvenir stalls", "backpacker market"],
    reveal: "Thai script, souvenir stalls, and backpacker density point back to Khao San Road.",
    fact: "Khao San has long been a hub for budget travel services and street markets.",
    lat: 13.7593,
    lng: 100.496588,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/De_compras_en_Khao_San_Road%2C_Bangkok%2C_Tailandia_%2835993308412%29.jpg/1920px-De_compras_en_Khao_San_Road%2C_Bangkok%2C_Tailandia_%2835993308412%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:De_compras_en_Khao_San_Road,_Bangkok,_Tailandia_(35993308412).jpg",
    attribution: "Edgardo W. Olivera, CC BY 2.0"
  },
  {
    id: "sg-marina-bay-sands",
    name: "Marina Bay",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Easy",
    clueTypes: ["waterfront skyline", "English signage", "modern district"],
    reveal: "The waterfront skyline and polished downtown setting point toward Marina Bay in Singapore.",
    fact: "Marina Bay is one of Singapore's most recognizable waterfront districts.",
    lat: 1.2836,
    lng: 103.8602,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg/1920px-ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg",
    attribution: "Basile Morin, CC BY-SA 4.0"
  },
  {
    id: "sg-chinatown-pagoda-street",
    name: "Pagoda Street",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Medium",
    clueTypes: ["heritage street", "Chinese signage", "dense shopfronts"],
    reveal: "Restored shophouses and Chinese signage point toward Singapore's Chinatown.",
    fact: "Pagoda Street is one of Chinatown's main visitor streets.",
    lat: 1.2835,
    lng: 103.8442,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Pagoda_Street_Chinatown_Singapore.jpg/1920px-Pagoda_Street_Chinatown_Singapore.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pagoda_Street_Chinatown_Singapore.jpg",
    attribution: "kallerna, CC BY-SA 4.0"
  },
  {
    id: "th-bangkok-siam-square",
    name: "Siam Square",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["shopping district", "local script", "urban rail"],
    reveal: "Elevated rail, large malls, and local script point toward Siam in central Bangkok.",
    fact: "Siam is one of Bangkok's major shopping and transit hubs.",
    lat: 13.7458,
    lng: 100.5347,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Rama_I_Road_in_central_Bangkok%2C_Thailand.jpg/1920px-Rama_I_Road_in_central_Bangkok%2C_Thailand.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rama_I_Road_in_central_Bangkok,_Thailand.jpg",
    attribution: "Vyacheslav Argenberg, CC BY 4.0"
  },
  {
    id: "th-chiang-mai-tha-phae",
    name: "Tha Phae Gate",
    city: "Chiang Mai",
    country: "Thailand",
    difficulty: "Hard",
    clueTypes: ["old city wall", "local script", "low-rise streets"],
    reveal: "Old city walls and lower-rise streets point toward Chiang Mai rather than Bangkok.",
    fact: "Tha Phae Gate is one of Chiang Mai Old City's best-known gates.",
    lat: 18.7877,
    lng: 98.9931,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/201703291115a_Chiang_Mai%2C_City_Wall%2C_Tha_Phae_Gate.jpg/1920px-201703291115a_Chiang_Mai%2C_City_Wall%2C_Tha_Phae_Gate.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:201703291115a_Chiang_Mai,_City_Wall,_Tha_Phae_Gate.jpg",
    attribution: "Hartmann Linge, CC BY-SA 3.0"
  },
  {
    id: "my-penang-armenian-street",
    name: "Armenian Street",
    city: "George Town",
    country: "Malaysia",
    difficulty: "Hard",
    clueTypes: ["heritage street", "low-rise shophouses", "mixed signage"],
    reveal: "Heritage shophouses and mixed signage point toward George Town, Penang.",
    fact: "Armenian Street is one of George Town's well-known heritage streets.",
    lat: 5.4154,
    lng: 100.3381,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Armenian_street-penang-190238953.jpg/1920px-Armenian_street-penang-190238953.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Armenian_street-penang-190238953.jpg",
    attribution: "RaffiKojian, CC BY 4.0"
  },
  {
    id: "my-kl-petaling-street",
    name: "Petaling Street",
    city: "Kuala Lumpur",
    country: "Malaysia",
    difficulty: "Medium",
    clueTypes: ["market street", "Chinese signage", "covered stalls"],
    reveal: "Market canopies and Chinese signage point toward Petaling Street in Kuala Lumpur.",
    fact: "Petaling Street is the main market street in Kuala Lumpur's Chinatown.",
    lat: 3.1431,
    lng: 101.6978,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Petaling_Street%2C_Kuala_Lumpur_01.jpg/1920px-Petaling_Street%2C_Kuala_Lumpur_01.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Petaling_Street,_Kuala_Lumpur_01.jpg",
    attribution: "IQRemix, CC BY-SA 2.0"
  },
  {
    id: "vn-hanoi-hoan-kiem",
    name: "Hoan Kiem Lake",
    city: "Hanoi",
    country: "Vietnam",
    difficulty: "Medium",
    clueTypes: ["lakefront road", "local signage", "old city"],
    reveal: "Lakefront streets and older urban fabric point toward Hanoi's Hoan Kiem area.",
    fact: "Hoan Kiem Lake anchors Hanoi's historic center.",
    lat: 21.0287,
    lng: 105.8522,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Hoan_Kiem_Lake_4123.jpg/1920px-Hoan_Kiem_Lake_4123.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hoan_Kiem_Lake_4123.jpg",
    attribution: "Ltn12345, CC BY-SA 4.0"
  },
  {
    id: "vn-da-nang-dragon-bridge",
    name: "Dragon Bridge",
    city: "Da Nang",
    country: "Vietnam",
    difficulty: "Hard",
    clueTypes: ["river crossing", "modern city", "local signage"],
    reveal: "A modern river crossing and central-city roads point toward Da Nang.",
    fact: "Dragon Bridge crosses the Han River in Da Nang.",
    lat: 16.0613,
    lng: 108.2278,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Da_Nang_Dragon_Bridge_%28I%29.jpg/1920px-Da_Nang_Dragon_Bridge_%28I%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Da_Nang_Dragon_Bridge_(I).jpg",
    attribution: "Supanut Arunoprayote, CC BY 4.0"
  },
  {
    id: "id-bali-kuta-beach",
    name: "Kuta Beach",
    city: "Bali",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["beach district", "tourist strip", "low-rise shops"],
    reveal: "Beachfront tourism and low-rise resort streets point toward Kuta, Bali.",
    fact: "Kuta is one of Bali's best-known beach districts.",
    lat: -8.7185,
    lng: 115.1686,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Kuta_Beach%2C_Bali%2C_20220825_1334_0839.jpg/1920px-Kuta_Beach%2C_Bali%2C_20220825_1334_0839.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kuta_Beach,_Bali,_20220825_1334_0839.jpg",
    attribution: "Jakub Halun, CC BY-SA 4.0"
  },
  {
    id: "id-bandung-braga",
    name: "Braga Street",
    city: "Bandung",
    country: "Indonesia",
    difficulty: "Hard",
    clueTypes: ["heritage street", "arcades", "low-rise shopfronts"],
    reveal: "A heritage commercial street with older facades points toward Bandung's Braga area.",
    fact: "Braga Street is one of Bandung's historic commercial corridors.",
    lat: -6.9175,
    lng: 107.6098,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Braga_Street_2023.jpg/1920px-Braga_Street_2023.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Braga_Street_2023.jpg",
    attribution: "Mhatopzz, CC BY 4.0"
  },
  {
    id: "ph-manila-intramuros",
    name: "Intramuros",
    city: "Manila",
    country: "Philippines",
    difficulty: "Hard",
    clueTypes: ["historic walls", "English signage", "old district"],
    reveal: "Historic walls and English signage point toward Manila's old walled district.",
    fact: "Intramuros is the historic walled area of Manila.",
    lat: 14.5896,
    lng: 120.9747,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Escuela_Taller%2C_Intramuros%2C_Manila%2C_Aug_2024.jpg/1920px-Escuela_Taller%2C_Intramuros%2C_Manila%2C_Aug_2024.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Escuela_Taller,_Intramuros,_Manila,_Aug_2024.jpg",
    attribution: "Ralff Nestor Nacor, CC BY-SA 4.0"
  },
  {
    id: "ph-bgc-high-street",
    name: "Bonifacio High Street",
    city: "Metro Manila",
    country: "Philippines",
    difficulty: "Medium",
    clueTypes: ["planned district", "English signage", "modern streets"],
    reveal: "A polished planned district with English-heavy signage points toward BGC.",
    fact: "Bonifacio Global City is a major business and lifestyle district in Metro Manila.",
    lat: 14.5507,
    lng: 121.0508,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Bonifacio_High_Street%2C_Metro_Manila.jpg/1920px-Bonifacio_High_Street%2C_Metro_Manila.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bonifacio_High_Street,_Metro_Manila.jpg",
    attribution: "Hans Olav Lien, Public domain"
  },
  {
    id: "kh-phnom-penh-riverside",
    name: "Riverside",
    city: "Phnom Penh",
    country: "Cambodia",
    difficulty: "Hard",
    clueTypes: ["riverfront road", "low-rise streets", "tourist strip"],
    reveal: "A broad riverfront and low-rise tourist-facing streets point toward Phnom Penh.",
    fact: "Phnom Penh's riverside follows the Tonle Sap and Mekong riverfront.",
    lat: 11.5683,
    lng: 104.9305,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Riverside_Park%2C_Phnom_Penh.jpg/1920px-Riverside_Park%2C_Phnom_Penh.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Riverside_Park,_Phnom_Penh.jpg",
    attribution: "Christophe95, CC BY-SA 4.0"
  },
  {
    id: "la-vientiane-patuxai",
    name: "Patuxai",
    city: "Vientiane",
    country: "Laos",
    difficulty: "Hard",
    clueTypes: ["monument road", "low-rise capital", "local script"],
    reveal: "A quieter low-rise capital setting and local script point toward Vientiane.",
    fact: "Patuxai is a prominent monument in central Vientiane.",
    lat: 17.9705,
    lng: 102.6188,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Patuxai%2C_Vientiane%2C_Laos_%285248396160%29.jpg/1920px-Patuxai%2C_Vientiane%2C_Laos_%285248396160%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Patuxai,_Vientiane,_Laos_(5248396160).jpg",
    attribution: "yeowatzup, CC BY 2.0"
  },
  {
    id: "mm-yangon-sule",
    name: "Sule Pagoda Road",
    city: "Yangon",
    country: "Myanmar",
    difficulty: "Hard",
    clueTypes: ["colonial blocks", "local script", "downtown grid"],
    reveal: "Colonial-era blocks, a downtown grid, and local script point toward central Yangon.",
    fact: "Sule Pagoda sits near the center of downtown Yangon.",
    lat: 16.7749,
    lng: 96.1588,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/20160815_Sule_Pagoda_Yangon_0307.jpg/1920px-20160815_Sule_Pagoda_Yangon_0307.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:20160815_Sule_Pagoda_Yangon_0307.jpg",
    attribution: "Jakub Halun, CC BY-SA 4.0"
  },
  {
    id: "bn-bandar-mosque",
    name: "Omar Ali Saifuddien Mosque",
    city: "Bandar Seri Begawan",
    country: "Brunei",
    difficulty: "Hard",
    clueTypes: ["quiet capital", "waterfront landmark", "tropical streets"],
    reveal: "Quiet tropical streets and an ornate waterfront landmark point toward Bandar Seri Begawan.",
    fact: "Omar Ali Saifuddien Mosque is one of Brunei's most recognizable landmarks.",
    lat: 4.8899,
    lng: 114.9398,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Omar_Ali_Saifuddien_Mosque%2C_Bandar_Seri_Begawan%2C_Brunei.jpg/1920px-Omar_Ali_Saifuddien_Mosque%2C_Bandar_Seri_Begawan%2C_Brunei.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Omar_Ali_Saifuddien_Mosque,_Bandar_Seri_Begawan,_Brunei.jpg",
    attribution: "Uhooep, CC BY-SA 4.0"
  }
];

export const REAL_VIEW_LOCATIONS = [
  ...GAME_ROUNDS.map(({ imageUrl, sourceUrl, attribution, ...round }) => round),
  {
    id: "sg-marina-bay",
    name: "Marina Bay",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Easy",
    clueTypes: ["waterfront road", "English signage", "high-rise district"],
    reveal: "A polished waterfront road grid, dense towers, and English signage are strong central Singapore clues.",
    fact: "Marina Bay is one of Singapore's main civic and business waterfront districts.",
    lat: 1.2836,
    lng: 103.8602
  },
  {
    id: "sg-bugis",
    name: "Bugis",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Medium",
    clueTypes: ["retail streets", "English signage", "dense city"],
    reveal: "Bugis mixes malls, narrow retail streets, and Singapore's clean dense streetscape.",
    fact: "Bugis is a central shopping and transit district in Singapore.",
    lat: 1.3006,
    lng: 103.8559
  },
  {
    id: "sg-chinatown",
    name: "Chinatown",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Medium",
    clueTypes: ["heritage street", "Chinese signage", "dense shopfronts"],
    reveal: "Restored shophouses and multilingual signage point toward Singapore's Chinatown area.",
    fact: "Singapore's Chinatown blends conserved shophouses with a major downtown transit area.",
    lat: 1.2842,
    lng: 103.8432
  },
  {
    id: "th-bangkok-sukhumvit",
    name: "Sukhumvit Road",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["local script", "wide road", "urban rail"],
    reveal: "Elevated rail, local script, and dense towers are common tells around Sukhumvit.",
    fact: "Sukhumvit is one of Bangkok's longest and busiest urban corridors.",
    lat: 13.7371,
    lng: 100.5607
  },
  {
    id: "th-bangkok-siam",
    name: "Siam Square",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["shopping district", "local script", "urban rail"],
    reveal: "Large malls, elevated rail, and local script point to central Bangkok's Siam area.",
    fact: "Siam is a major shopping and interchange district in Bangkok.",
    lat: 13.7458,
    lng: 100.5347
  },
  {
    id: "th-chiang-mai-old-city",
    name: "Chiang Mai Old City",
    city: "Chiang Mai",
    country: "Thailand",
    difficulty: "Hard",
    clueTypes: ["low-rise streets", "local script", "old city grid"],
    reveal: "Low-rise northern city streets and local script can point away from Bangkok toward Chiang Mai.",
    fact: "Chiang Mai's old city is enclosed by historic moats and remnants of city walls.",
    lat: 18.7883,
    lng: 98.9853
  },
  {
    id: "th-pattaya-beach-road",
    name: "Beach Road",
    city: "Pattaya",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["coastal road", "tourist strip", "local script"],
    reveal: "A coastal tourist road with local script and resort frontage fits Pattaya.",
    fact: "Pattaya is a major beach city southeast of Bangkok.",
    lat: 12.9367,
    lng: 100.8834
  },
  {
    id: "my-kl-bukit-bintang",
    name: "Bukit Bintang",
    city: "Kuala Lumpur",
    country: "Malaysia",
    difficulty: "Medium",
    clueTypes: ["shopping district", "English signage", "dense shopfronts"],
    reveal: "Bukit Bintang's retail density, mixed signage, and towers are central Kuala Lumpur clues.",
    fact: "Bukit Bintang is Kuala Lumpur's main shopping and entertainment district.",
    lat: 3.1468,
    lng: 101.7113
  },
  {
    id: "my-klcc",
    name: "KLCC",
    city: "Kuala Lumpur",
    country: "Malaysia",
    difficulty: "Easy",
    clueTypes: ["high-rise district", "wide avenue", "English signage"],
    reveal: "A polished high-rise district and broad central avenues point toward KLCC.",
    fact: "KLCC surrounds the Petronas Twin Towers in central Kuala Lumpur.",
    lat: 3.1579,
    lng: 101.7121
  },
  {
    id: "my-george-town-chulia",
    name: "Chulia Street",
    city: "George Town",
    country: "Malaysia",
    difficulty: "Hard",
    clueTypes: ["heritage street", "low-rise shophouses", "mixed signage"],
    reveal: "Heritage shophouses and mixed signage point toward George Town's old core.",
    fact: "George Town is a UNESCO-listed historic city on Penang Island.",
    lat: 5.4192,
    lng: 100.3375
  },
  {
    id: "my-johor-bahru-city-square",
    name: "City Square",
    city: "Johor Bahru",
    country: "Malaysia",
    difficulty: "Hard",
    clueTypes: ["shopping district", "mixed signage", "border city"],
    reveal: "Dense malls and mixed signage can fit Johor Bahru's city center.",
    fact: "Johor Bahru sits across the causeway from Singapore.",
    lat: 1.4628,
    lng: 103.7649
  },
  {
    id: "vn-hcmc-nguyen-hue",
    name: "Nguyen Hue Boulevard",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    difficulty: "Medium",
    clueTypes: ["wide boulevard", "dense towers", "local signage"],
    reveal: "A broad pedestrian boulevard, dense towers, and local signage point to central Ho Chi Minh City.",
    fact: "Nguyen Hue is a major ceremonial boulevard in Ho Chi Minh City.",
    lat: 10.7731,
    lng: 106.7042
  },
  {
    id: "vn-hcmc-ben-thanh",
    name: "Ben Thanh",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    difficulty: "Medium",
    clueTypes: ["market district", "local signage", "dense traffic"],
    reveal: "Market frontage, dense motorbike traffic, and local signage point toward central Ho Chi Minh City.",
    fact: "Ben Thanh Market is one of Ho Chi Minh City's best-known landmarks.",
    lat: 10.7724,
    lng: 106.6980
  },
  {
    id: "vn-hanoi-hoan-kiem",
    name: "Hoan Kiem Lake",
    city: "Hanoi",
    country: "Vietnam",
    difficulty: "Medium",
    clueTypes: ["lakefront road", "local signage", "old city"],
    reveal: "Lakefront roads, older urban fabric, and local signage point toward central Hanoi.",
    fact: "Hoan Kiem Lake anchors Hanoi's historic center.",
    lat: 21.0287,
    lng: 105.8522
  },
  {
    id: "vn-da-nang-bach-dang",
    name: "Bach Dang Street",
    city: "Da Nang",
    country: "Vietnam",
    difficulty: "Hard",
    clueTypes: ["riverfront road", "local signage", "modern city"],
    reveal: "A riverfront boulevard with modern mid-rise development points toward Da Nang.",
    fact: "Da Nang sits on the Han River and is one of central Vietnam's largest cities.",
    lat: 16.0678,
    lng: 108.2245
  },
  {
    id: "id-jakarta-thamrin",
    name: "Jalan Thamrin",
    city: "Jakarta",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["wide avenue", "business district", "busway corridor"],
    reveal: "Very wide avenues, bus corridors, and high-rise density point toward central Jakarta.",
    fact: "Jalan Thamrin is one of Jakarta's core business avenues.",
    lat: -6.1931,
    lng: 106.8230
  },
  {
    id: "id-jakarta-kota-tua",
    name: "Kota Tua",
    city: "Jakarta",
    country: "Indonesia",
    difficulty: "Hard",
    clueTypes: ["historic district", "colonial buildings", "urban square"],
    reveal: "Older colonial fabric and open squares distinguish Kota Tua from Jakarta's newer CBD.",
    fact: "Kota Tua is Jakarta's old town around the former Dutch colonial center.",
    lat: -6.1352,
    lng: 106.8133
  },
  {
    id: "id-bandung-braga",
    name: "Braga Street",
    city: "Bandung",
    country: "Indonesia",
    difficulty: "Hard",
    clueTypes: ["heritage street", "arcades", "low-rise shopfronts"],
    reveal: "A heritage commercial street with older facades fits Bandung's Braga area.",
    fact: "Braga Street is one of Bandung's historic commercial streets.",
    lat: -6.9175,
    lng: 107.6098
  },
  {
    id: "id-bali-kuta",
    name: "Kuta",
    city: "Bali",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["tourist strip", "low-rise shops", "beach district"],
    reveal: "Low-rise tourist shops and resort traffic can point toward Bali's Kuta area.",
    fact: "Kuta is one of Bali's most famous beach and nightlife districts.",
    lat: -8.7185,
    lng: 115.1686
  },
  {
    id: "id-surabaya-tunjungan",
    name: "Tunjungan",
    city: "Surabaya",
    country: "Indonesia",
    difficulty: "Hard",
    clueTypes: ["wide city road", "commercial district", "local signage"],
    reveal: "A large commercial district with broad roads can fit central Surabaya.",
    fact: "Tunjungan is a major historic and commercial corridor in Surabaya.",
    lat: -7.2607,
    lng: 112.7384
  },
  {
    id: "ph-manila-intramuros",
    name: "Intramuros",
    city: "Manila",
    country: "Philippines",
    difficulty: "Hard",
    clueTypes: ["historic walls", "English signage", "old district"],
    reveal: "Historic walls and English signage point toward Manila's old walled district.",
    fact: "Intramuros is the historic walled area of Manila.",
    lat: 14.5896,
    lng: 120.9747
  },
  {
    id: "ph-bgc-high-street",
    name: "Bonifacio High Street",
    city: "Metro Manila",
    country: "Philippines",
    difficulty: "Medium",
    clueTypes: ["planned district", "English signage", "modern streets"],
    reveal: "A polished planned district with English-heavy signs points toward BGC.",
    fact: "Bonifacio Global City is a major business and lifestyle district in Metro Manila.",
    lat: 14.5507,
    lng: 121.0508
  },
  {
    id: "ph-cebu-it-park",
    name: "Cebu IT Park",
    city: "Cebu City",
    country: "Philippines",
    difficulty: "Hard",
    clueTypes: ["business district", "English signage", "tropical city"],
    reveal: "English signage, newer business blocks, and tropical streets can point toward Cebu.",
    fact: "Cebu IT Park is one of Cebu City's main business districts.",
    lat: 10.3307,
    lng: 123.9070
  },
  {
    id: "kh-phnom-penh-riverside",
    name: "Riverside",
    city: "Phnom Penh",
    country: "Cambodia",
    difficulty: "Hard",
    clueTypes: ["riverfront road", "low-rise streets", "tourist strip"],
    reveal: "A broad riverfront, low-rise blocks, and tourist-facing streets point toward Phnom Penh.",
    fact: "Phnom Penh's riverside follows the Tonle Sap and Mekong riverfront.",
    lat: 11.5683,
    lng: 104.9305
  },
  {
    id: "kh-siem-reap-old-market",
    name: "Old Market",
    city: "Siem Reap",
    country: "Cambodia",
    difficulty: "Medium",
    clueTypes: ["tourist market", "low-rise shopfronts", "English signage"],
    reveal: "Low-rise tourist-market streets and English-facing shopfronts point toward Siem Reap.",
    fact: "Siem Reap is the main gateway city for the Angkor temple region.",
    lat: 13.3535,
    lng: 103.8555
  },
  {
    id: "la-vientiane-riverside",
    name: "Mekong Riverside",
    city: "Vientiane",
    country: "Laos",
    difficulty: "Hard",
    clueTypes: ["riverfront road", "low-rise capital", "local script"],
    reveal: "A quieter low-rise capital city with local script and riverfront roads points toward Vientiane.",
    fact: "Vientiane sits along the Mekong River near the border with Thailand.",
    lat: 17.9641,
    lng: 102.6054
  },
  {
    id: "la-luang-prabang-night-market",
    name: "Night Market Street",
    city: "Luang Prabang",
    country: "Laos",
    difficulty: "Hard",
    clueTypes: ["heritage street", "low-rise shops", "local script"],
    reveal: "Low-rise heritage streets and local script point toward Luang Prabang.",
    fact: "Luang Prabang is a UNESCO-listed city in northern Laos.",
    lat: 19.8868,
    lng: 102.1350
  },
  {
    id: "mm-yangon-sule",
    name: "Sule Pagoda Road",
    city: "Yangon",
    country: "Myanmar",
    difficulty: "Hard",
    clueTypes: ["colonial blocks", "local script", "downtown grid"],
    reveal: "Colonial-era blocks, a downtown grid, and local script point toward central Yangon.",
    fact: "Sule Pagoda sits near the center of downtown Yangon.",
    lat: 16.7749,
    lng: 96.1588
  },
  {
    id: "mm-mandalay-palace-road",
    name: "Palace Road",
    city: "Mandalay",
    country: "Myanmar",
    difficulty: "Hard",
    clueTypes: ["wide road", "local script", "low-rise city"],
    reveal: "Wide low-rise roads and local script can point toward Mandalay.",
    fact: "Mandalay was the last royal capital of Myanmar.",
    lat: 21.9588,
    lng: 96.0891
  },
  {
    id: "bn-bandar-seri-begawan",
    name: "City Centre",
    city: "Bandar Seri Begawan",
    country: "Brunei",
    difficulty: "Hard",
    clueTypes: ["quiet capital", "wide road", "tropical streets"],
    reveal: "Quiet tropical roads and low-rise capital-city streets can point toward Bandar Seri Begawan.",
    fact: "Bandar Seri Begawan is Brunei's capital city.",
    lat: 4.8903,
    lng: 114.9422
  }
];
