export const GAME_ROUNDS = [
  {
    id: "sg-orchard-road",
    name: "Orchard Road",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Easy",
    clueTypes: ["retail corridor", "English signage", "dense city"],
    reveal: "Orchard Road is Singapore's best-known shopping belt, so polished malls, wide sidewalks, and English-heavy signs are strong clues.",
    fact: "The Orchard district began as an area of nutmeg, pepper, and fruit orchards before becoming a retail spine.",
    lat: 1.303989,
    lng: 103.83345,
    imageUrl: "./assets/rounds/sg-orchard-road.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Orchard_Road,_Singapore_(June_26,_2023)_pedestrians.jpg",
    attribution: "Sharon Hahn Darlin, CC BY 2.0"
  },
  {
    id: "th-bangkok-khao-san-road",
    name: "Khao San Road",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["Thai script", "backpacker street", "street market"],
    reveal: "Thai script, dense shopfronts, and backpacker-market energy point toward Bangkok's Khao San Road.",
    fact: "Khao San Road became internationally famous as a backpacker hub near Bangkok's old city.",
    lat: 13.759738,
    lng: 100.495676,
    imageUrl: "./assets/rounds/th-bangkok-khao-san-road.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Khao_San_Road,_Bangkok,_Tailandia_(37594114336).jpg",
    attribution: "Edgardo W. Olivera, CC BY 2.0"
  },
  {
    id: "th-phuket-bangla-road",
    name: "Bangla Road",
    city: "Phuket",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["Thai script", "nightlife", "tourist strip"],
    reveal: "Bangla Road's nightlife signage and Patong resort feel separate it from Bangkok's older street markets.",
    fact: "Bangla Road sits in Patong, one of Phuket's busiest nightlife and beach districts.",
    lat: 7.893422,
    lng: 98.297367,
    imageUrl: "./assets/rounds/th-phuket-bangla-road.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bangla_Road_Patong_Thajsko_2018_4.jpg",
    attribution: "Karelj, Public domain"
  },
  {
    id: "my-kuala-lumpur-jalan-alor",
    name: "Jalan Alor",
    city: "Kuala Lumpur",
    country: "Malaysia",
    difficulty: "Easy",
    clueTypes: ["food stalls", "Chinese signage", "Malaysia flag"],
    reveal: "Jalan Alor is a food street in Bukit Bintang; mixed Chinese/English signage and Malaysian flags are useful tells.",
    fact: "Jalan Alor is one of Kuala Lumpur's best-known open-air dining streets.",
    lat: 3.145644,
    lng: 101.708619,
    imageUrl: "./assets/rounds/my-kuala-lumpur-jalan-alor.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jalan_Alor_Kuala_Lumpur.jpg",
    attribution: "Alexander Synaptic, CC BY-SA 4.0"
  },
  {
    id: "vn-hcmc-bui-vien",
    name: "Bui Vien Street",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    difficulty: "Medium",
    clueTypes: ["Vietnamese signage", "night street", "dense shopfronts"],
    reveal: "Vietnamese diacritics on signs and the narrow nightlife street scene point toward Bui Vien in Ho Chi Minh City.",
    fact: "Bui Vien is often called Ho Chi Minh City's backpacker street.",
    lat: 10.766556,
    lng: 106.692111,
    imageUrl: "./assets/rounds/vn-hcmc-bui-vien.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bui_Vien_Street,_Ho_Chi_Minh_City,_at_night,_2023_(07).jpg",
    attribution: "Bahnfrend, CC BY-SA 4.0"
  },
  {
    id: "kh-siem-reap-pub-street",
    name: "Pub Street",
    city: "Siem Reap",
    country: "Cambodia",
    difficulty: "Medium",
    clueTypes: ["tourist street", "English signage", "low-rise shophouses"],
    reveal: "Pub Street's tourist-facing English signs and Siem Reap shophouse look distinguish it from bigger capitals.",
    fact: "Pub Street is a nightlife and restaurant area near the Angkor temple tourism circuit.",
    lat: 13.360173,
    lng: 103.856122,
    imageUrl: "./assets/rounds/kh-siem-reap-pub-street.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pub_Street,_Siem_Reap.jpg",
    attribution: "Radoslaw Botev, CC BY 3.0 PL"
  },
  {
    id: "vn-hanoi-ta-hien",
    name: "Ta Hien Street",
    city: "Hanoi",
    country: "Vietnam",
    difficulty: "Hard",
    clueTypes: ["Old Quarter", "Vietnamese signage", "narrow street"],
    reveal: "Narrow lanes, older facades, and Vietnamese signage are a strong Hanoi Old Quarter pattern.",
    fact: "Ta Hien is one of Hanoi Old Quarter's best-known social streets.",
    lat: 21.034711,
    lng: 105.852142,
    imageUrl: "./assets/rounds/vn-hanoi-ta-hien.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:T%E1%BA%A1_Hi%E1%BB%87n_Street,_Hanoi,_Vietnam_13.jpg",
    attribution: "Ltn12345, CC BY-SA 4.0"
  },
  {
    id: "my-malacca-jonker-walk",
    name: "Jonker Walk",
    city: "Malacca",
    country: "Malaysia",
    difficulty: "Medium",
    clueTypes: ["heritage street", "Chinese signage", "colonial shophouses"],
    reveal: "The heritage arch, shophouses, and mixed Chinese/Malaysian visual language point to Jonker Walk.",
    fact: "Jonker Walk runs through Malacca's UNESCO-listed historic core.",
    lat: 2.198153,
    lng: 102.244692,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Malacca_Malaysia_Jonker-Walk-Arch-and-Tamil-Methodist-Church-01.jpg/1920px-Malacca_Malaysia_Jonker-Walk-Arch-and-Tamil-Methodist-Church-01.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Malacca_Malaysia_Jonker-Walk-Arch-and-Tamil-Methodist-Church-01.jpg",
    attribution: "CEphoto, Uwe Aranas, CC BY-SA 3.0"
  },
  {
    id: "ph-makati-avenue",
    name: "Makati Avenue",
    city: "Metro Manila",
    country: "Philippines",
    difficulty: "Hard",
    clueTypes: ["English signage", "CBD skyline", "wide avenue"],
    reveal: "English-heavy urban signage and the dense Makati business district feel point toward Metro Manila.",
    fact: "Makati is one of the Philippines' major financial and commercial centers.",
    lat: 14.552662,
    lng: 121.023137,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Makati_Avenue%2C_Feb_2025.jpg/1920px-Makati_Avenue%2C_Feb_2025.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Makati_Avenue,_Feb_2025.jpg",
    attribution: "Ralff Nestor Nacor, CC BY-SA 4.0"
  },
  {
    id: "id-jakarta-sudirman",
    name: "Jalan Sudirman",
    city: "Jakarta",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["business district", "Indonesian road name", "high-rise corridor"],
    reveal: "The wide CBD corridor and Indonesian 'Jalan' road naming are strong Jakarta clues.",
    fact: "Jalan Sudirman is part of Jakarta's central business spine.",
    lat: -6.210986,
    lng: 106.819795,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Jalan_Sudirman%2C_Jakarta_-_panoramio.jpg/1920px-Jalan_Sudirman%2C_Jakarta_-_panoramio.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jalan_Sudirman,_Jakarta_-_panoramio.jpg",
    attribution: "Mozhar, CC BY-SA 3.0"
  },
  {
    id: "id-yogyakarta-malioboro",
    name: "Malioboro Street",
    city: "Yogyakarta",
    country: "Indonesia",
    difficulty: "Medium",
    clueTypes: ["Indonesian signage", "arcades", "heritage shopping street"],
    reveal: "Malioboro's covered walkways and Indonesian street-market feel mark it as Yogyakarta.",
    fact: "Malioboro is one of Yogyakarta's most famous shopping and cultural streets.",
    lat: -7.7926,
    lng: 110.3658,
    imageUrl: "./assets/rounds/id-yogyakarta-malioboro.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Malioboro_Street,_Yogyakarta.JPG",
    attribution: "Gunawan Kartapranata, CC BY-SA 3.0"
  },
  {
    id: "sg-ion-orchard",
    name: "ION Orchard",
    city: "Singapore",
    country: "Singapore",
    difficulty: "Easy",
    clueTypes: ["luxury mall", "English signage", "clean streetscape"],
    reveal: "ION Orchard's distinctive mall frontage and English-heavy shopping corridor are very Singapore.",
    fact: "ION Orchard is one of the landmark malls along Orchard Road.",
    lat: 1.304342,
    lng: 103.831772,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/ION_Orchard_and_Orchard_Road%2C_Singapore_%2842345667100%29.jpg/1920px-ION_Orchard_and_Orchard_Road%2C_Singapore_%2842345667100%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ION_Orchard_and_Orchard_Road,_Singapore_(42345667100).jpg",
    attribution: "Fabio Achilli, CC BY 2.0"
  },
  {
    id: "th-bangkok-khao-san-market",
    name: "Khao San Road Market",
    city: "Bangkok",
    country: "Thailand",
    difficulty: "Medium",
    clueTypes: ["Thai script", "souvenir stalls", "backpacker market"],
    reveal: "Thai script, souvenir stalls, and backpacker density point back to Khao San Road.",
    fact: "Khao San has long been a hub for budget travel services and street markets.",
    lat: 13.7593,
    lng: 100.496588,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/De_compras_en_Khao_San_Road%2C_Bangkok%2C_Tailandia_%2835993308412%29.jpg/1920px-De_compras_en_Khao_San_Road%2C_Bangkok%2C_Tailandia_%2835993308412%29.jpg",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:De_compras_en_Khao_San_Road,_Bangkok,_Tailandia_(35993308412).jpg",
    attribution: "Edgardo W. Olivera, CC BY 2.0"
  }
];
